---
- name: Configure the filesystem
  ansible.builtin.import_playbook: ./fs-check-remediation/setup.yml

- name: Remediate the filesystem if needed
  ansible.builtin.import_playbook: ./fs-check-remediation/fs_remediate.yml
