---
- name: Post an update on the Work Note section of Service Now Incident
  hosts: localhost

  tasks:
    - name: Post Work Note on SNOW
      ansible.builtin.import_tasks: "./tasks/snow_post_worknote_tasks.yml"
      vars:
        post_message: Resolution automation applied successful by AAP

    - name: Closing the incident on SNOW
      servicenow.itsm.incident:
        instance:
          host: "{{ snow_instance }}"
          username: "{{ snow_user }}"
          password: "{{ snow_pass }}"
        number: "{{ snow_inc_number }}"
        state: resolved
        close_code: "Known error"
        close_notes: "Resolution automation applied successful by AAP"
